Diiid shawn
ORNL-Fusion/OEDGE pull request #4
Opened 2023-04-10 23:31 UTC by shawnzamperini

Code related to:
 - Prompt redeposition of W
 - Ballooning transport approximation
 - Inward hole-like transport for blob-like impurity transport model
 - Core pinch option
 - Laid groundwork for TiB2 and ZrB2 simulations using TrimSP calculated yields (ADAS data is missing though)
 - Minor bug fix in "SMAX ERROR" printing too early

2023-04-21 18:40 UTC, jdelder requested changes

2023-04-21 18:40 UTC, jdelder commented on comsrc/sputter.f
You set IDATA to 7*.true., .false below for the four tiB2/ZrB2 sputtering yields added. This data is used and is copied to CIDATA. The array indicates when sputtering yield data is available for the specified target material based on plasma material. In this case 7*.true., .false. is saying that the code provides yields for all of these on the specified target material except Silicon. ' H    ',' D    ',' T    ',' HE4  ',' C    ',' SELF ',' O    ',  ' Si   ' ...

2023-04-21 18:40 UTC, jdelder commented on comsrc/sputter.f
Hi Shawn, 
I was working on something else when I noticed that in mod_sol29 you assign values to kteds and knds which are supposed to be the data at the targets. The code assigns the values from the middle of the first cell on the mesh. Usually, kteds etc get the input values for the target conditions that are used as the starting point of the along ring calculations. The cell center values of the first grid cell are typically different and in some cases substantially different from the target values (there are some very steep gradients near the target). Could you check your treatment of the target conditions in sol29 and what you are doing with these values?
Cheers, 
David

2023-04-21 18:40 UTC, jdelder commented on comsrc/sputter.f
nrand and seed were added to the call to promptdep. Seed shouldn't need to be passed around since it is only used at the very beginning of the run to seed the random number generator and should not be used again as far as I know. nrand is used as a argument to the surand call asking for a specific number of random numbers to be pre-loaded into the random number array and so also isn't required to be passed in - filling of the random number arrays that used the old code which called the random number generator all at once to save execution time - is done from div.f in the main particle loop and is only useful for the code that uses the pre-loaded random numbers. In general, if random numbers are used, it is better to use the subroutine getran(rand) or the function getranf which are both in the sysgcc.f file. 

The number of random numbers used by the code is tracked using the ran_used variable which is in the rand_data module and it is not passed around.

2023-04-21 18:40 UTC, jdelder commented on div6/src/tau.f
The exponential operator in fortran is ** ... and it is clearer to use that rather than repeating elements twice which is more prone to bugs.
eg sqrt(bts(ik,ir)**2 + (bts(ik,ir)*bratio(ik,ir))**2)

2023-04-24 15:56 UTC, shawnzamperini commented on comsrc/sputter.f
> You set IDATA to 7*.true., .false below...

Fixed. Only data for deuterium is available.

> I was working on something else when I noticed that in mod_sol29 you assign...

SOL29 is different from the other options in that it doesn't build a solution from the target up. The thinking is "what if target conditions were some sort of statistical average of the impacting blob characteristics". So it does not actually take in any input target data. The target arrays within SOL29 get overwritten in the initialization with constant seed values (e.g., 10 eV) and then get overwritten each iteration as the solution converges on the blob-averaged target profiles. The physics behind this is by no means firmly established. SOL29 is mostly just a fun little "what-if" project of mine and I would not encourage anyone to use it yet (though as it stands it does currently work as intended). So what you describe in your comment is the intended function.

> nrand and seed were added to the call to promptdep...

Ah, this makes sense and seems like the more modern approach. Fixed that within promptdep.

2023-04-24 15:56 UTC, shawnzamperini commented on div6/src/tau.f
Swapped with exponent operator in tau.f and ion_crossfield_transport.f.

2023-05-02 18:02 UTC, jdelder approved these changes

2023-05-02 18:02 UTC, merged